package org.coderfun.boot.core.service;

import org.coderfun.boot.core.entity.Role;

import klg.common.dataaccess.BaseService;



/**
 *
 * 
 * Generated by fieldmeta at 2018-09-20T21:15:17+08:00
 *
 */
 
public interface RoleService extends BaseService<Role, Long>{
	
}
