package org.coderfun.boot.core.service;

import klg.common.dataaccess.BaseService;

import java.util.List;

import org.coderfun.boot.core.entity.RolePermission;
import org.springframework.data.repository.query.Param;



/**
 *
 * 
 * Generated by fieldmeta at 2018-10-23T14:08:29+08:00
 *
 */
 
public interface RolePermissionService extends BaseService<RolePermission, Long>{

	public List<Long> findPermissionIdsByRoleId(Long roleId);

	public void updateRolePermissions(Long roleId, List<Long> permissionIds);
	
	public void deleteInBatchByRoleId(Long roleId);
	
	public void deleteInBatchByPermissionId(Long permissionId);
	
}
