package org.coderfun.boot.core.service;

import java.util.List;

import org.coderfun.boot.core.entity.UserRole;
import org.springframework.data.repository.query.Param;

import klg.common.dataaccess.BaseService;



/**
 *
 * 
 * Generated by fieldmeta at 2018-10-23T14:08:29+08:00
 *
 */
 
public interface UserRoleService extends BaseService<UserRole, Long>{

	public List<Long> findRoleIdsByUserId(Long userId);
	
	public void deleteInBatchByUserId(Long userId);

	public void updateUserRoles(Long userId, List<Long> roleIds);
	
}
