package org.coderfun.member.core.service;

import org.coderfun.member.core.entity.Member;

import klg.common.dataaccess.BaseService;

/**
 *
 * 
 * Generated by fieldmeta at 2018-12-11T21:24:49+08:00
 *
 */

public interface MemberService extends BaseService<Member, Long> {
	
	public Member getByEmail(String email);
	public Member getByUsername(String username);
	public Member getByMobile(String mobile);
	
	public boolean checkPassword(Member member);
	
	public boolean checkUsernameExist(String username);
	public boolean checkEmailExist(String email);
	public boolean checkMobileExist(String mobile);
	
	public Member create(Member member);

	/**
	 * 
	 * 并重新设置盐，并对密码进行加密，管理员调用
	 * 
	 * @param userId
	 * @param plainPassword
	 */
	
	public void updatePassword(Long memberId,String plainPassword);
	
	/**
	 * 用户调用
	 * 
	 * @param userId
	 * @param oldPlainPassword
	 * @param newPlainPassword
	 */
	public void changePassword(Long memberId,String oldPlainPassword,String newPlainPassword);
}
