package org.coderfun.common.log.dao;

import klg.common.dataaccess.BaseRepository;
import org.coderfun.common.log.entity.LoginLog;


/**
 *
 * 
 * Generated by fieldmeta at 2018-11-23T22:34:30+08:00
 *
 */

public interface LoginLogDAO extends BaseRepository<LoginLog, Long> {

}
