package org.coderfun.common.log.dao;

import klg.common.dataaccess.BaseRepository;
import org.coderfun.common.log.entity.SysLog;


/**
 *
 * 
 * Generated by fieldmeta at 2018-11-23T15:14:20+08:00
 *
 */

public interface SysLogDAO extends BaseRepository<SysLog, Long> {

}
