package org.coderfun.boot.core.dao;

import org.coderfun.boot.core.entity.Permission;

import klg.common.dataaccess.BaseRepository;


/**
 *
 * 
 * Generated by fieldmeta at 2018-09-20T21:15:17+08:00
 *
 */

public interface PermissionDAO extends BaseRepository<Permission, Long> {
	
}
