package org.coderfun.boot.core.dao;

import org.coderfun.boot.core.entity.Role;

import klg.common.dataaccess.BaseRepository;


/**
 *
 * 
 * Generated by fieldmeta at 2018-09-20T21:15:17+08:00
 *
 */

public interface RoleDAO extends BaseRepository<Role, Long> {
	
}
