package org.coderfun.boot.core.dao;

import java.util.List;

import org.coderfun.boot.core.entity.Permission;
import org.coderfun.boot.core.entity.User;
import org.springframework.data.repository.query.Param;

import com.slyak.spring.jpa.TemplateQuery;

import klg.common.dataaccess.BaseRepository;


/**
 *
 * 
 * Generated by fieldmeta at 2018-09-20T21:15:17+08:00
 *
 */

public interface UserDAO extends BaseRepository<User, Long> {

	@TemplateQuery
	public List<Long> queryMenuIds(@Param("userId") Long userId);

	@TemplateQuery
	public List<String> queryMenuUrls(@Param("userId") Long userId);
	
	@TemplateQuery
	public List<String> queryPermissions(@Param("userId") Long userId);
	
}
