mysql.username=paas
mysql.password=q16G_EMwJ5n_dpPLvmRa_ss2r
mysql.url=jdbc:mysql://172.31.253.229:3306/crm3?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai&autoReconnect=true&allowMultiQueries=true&nullCatalogMeansCurrent=true
mysql.dbname=crm3
mysql.tables=paas_user_rights_config
#mysql.username=root
#mysql.password=mysqladmin
#mysql.url=jdbc:mysql://localhost:3307/db_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#mysql.dbname=db_test
#mysql.tables=biz_test



package.path=net.trueland.scrm.paas.runtime.extender.tenant

path.entity=/runtime-model/src/main/java/net/trueland/scrm/paas/runtime/extender/tenant/model/entity
path.xml=/runtime-server/src/main/resources/mapper
path.mapper=/runtime-server/src/main/java/net/trueland/scrm/paas/runtime/extender/tenant/mapper
path.service=/runtime-server/src/main/java/net/trueland/scrm/paas/runtime/extender/tenant/service
path.serviceImpl=/runtime-server/src/main/java/net/trueland/scrm/paas/runtime/extender/tenant/service/impl
path.controller=/runtime-server/src/main/java/net/trueland/scrm/paas/runtime/extender/tenant/controller