
# 数据源配置
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password:
        url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8

server:
    port: 6666
# MyBatis配置
mybatis:
    # 搜索指定包别名
#    typeAliasesPackage: com.hp.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:**/generator/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
