package org.coderfun.common.log.service;

import klg.common.dataaccess.BaseService;
import org.coderfun.common.log.entity.LoginLog;



/**
 *
 * 
 * Generated by fieldmeta at 2018-11-23T22:34:30+08:00
 *
 */
 
public interface LoginLogService extends BaseService<LoginLog, Long>{

}
