package org.coderfun.common.log.service;

import klg.common.dataaccess.BaseService;
import org.coderfun.common.log.entity.SysLog;



/**
 *
 * 
 * Generated by fieldmeta at 2018-11-23T15:14:20+08:00
 *
 */
 
public interface SysLogService extends BaseService<SysLog, Long>{

}
